name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    # Declare permissions similar to the Docker workflow template
    permissions:
      contents: read        # Needed for checking out the repository
      packages: write       # Needed for publishing to GitHub Packages

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Install Bun
      - name: Install npm
        run: npm install -g npm@latest

      # Step 3: Install Dependencies
      - name: Install Dependencies
        run: npm install

      # Step 4: Run Typecheck
      - name: Run Typecheck
        run: npm run typecheck

      # Step 5: Run Tests with Coverage
      - name: Run Tests with Coverage
        run: npn run coverage

      # Step 6: Upload Coverage Artifact
      - name: Upload Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage

      # Step 7: Authenticate with GitHub Packages
      # Write the correct npm registry auth token so that Bun (npm under the hood) can publish.
      - name: Authenticate with GitHub Packages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "//npm.pkg.github.com/:_authToken=${GITHUB_TOKEN}" > ~/.npmrc

      # Step 8: Publish Package to GitHub Packages
      - name: Publish Package
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm publish