name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Install Bun
      - name: Install Bun
        run: |
          curl -fsSL https://bun.sh/install | bash
          # Add Bun's binary directory to the PATH
          echo "${HOME}/.bun/bin" >> $GITHUB_PATH

      # Step 3: Install Dependencies
      - name: Install Dependencies
        run: bun install

      # Step 4: Run Typecheck
      - name: Run Typecheck
        run: bun run typecheck

      # Step 5: Run Tests with Coverage
      - name: Run Tests with Coverage
        run: bun run coverage

      # Step 6: Upload Coverage Artifact
      - name: Upload Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage

      # Step 7: Authenticate with npm
      - name: Authenticate with npm
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN2 }}" > ~/.npmrc

      # Step 8: Publish Package to GitHub Packages
      - name: Publish Package
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: bun publish